blank_issues_enabled: false
contact_links:
  - name: Security vulnerability
    url: https://github.com/joaomede/langgraph-supervised-quickstart/security/advisories/new
    about: Please report security issues privately via GitHub Security Advisories.
  - name: Documentation
    url: https://github.com/joaomede/langgraph-supervised-quickstart/tree/main/docs
    about: Read guides and examples in the docs folder.